const languageCodes = [
  { label: "Abkhaz", key: "ab" },
  { label: "Acehnese", key: "ace" },
  { label: "Acholi", key: "ach" },
  { label: "Afrikaans", key: "af" },
  { label: "Albanian", key: "sq" },
  { label: "Alur", key: "alz" },
  { label: "Amharic", key: "am" },
  { label: "Arabic", key: "ar" },
  { label: "Armenian", key: "hy" },
  { label: "Assamese", key: "as" },
  { label: "Awadhi", key: "awa" },
  { label: "Aymara", key: "ay" },
  { label: "Azerbaijani", key: "az" },
  { label: "Balinese", key: "ban" },
  { label: "Bambara", key: "bm" },
  { label: "Bashkir", key: "ba" },
  { label: "Basque", key: "eu" },
  { label: "Batak Karo", key: "btx" },
  { label: "Batak Simalungun", key: "bts" },
  { label: "Batak Toba", key: "bbc" },
  { label: "Belarusian", key: "be" },
  { label: "Bemba", key: "bem" },
  { label: "Bengali", key: "bn" },
  { label: "Betawi", key: "bew" },
  { label: "Bhojpuri", key: "bho" },
  { label: "Bikol", key: "bik" },
  { label: "Bosnian", key: "bs" },
  { label: "Breton", key: "br" },
  { label: "Bulgarian", key: "bg" },
  { label: "Buryat", key: "bua" },
  { label: "Cantonese", key: "yue" },
  { label: "Catalan", key: "ca" },
  { label: "Cebuano", key: "ceb" },
  { label: "Chichewa (Nyanja)", key: "ny" },
  { label: "Chinese (Simplified)", key: "zh-CN" },
  { label: "Chinese (Traditional)", key: "zh-TW" },
  { label: "Chuvash", key: "cv" },
  { label: "Corsican", key: "co" },
  { label: "Crimean Tatar", key: "crh" },
  { label: "Croatian", key: "hr" },
  { label: "Czech", key: "cs" },
  { label: "Danish", key: "da" },
  { label: "Dinka", key: "din" },
  { label: "Divehi", key: "dv" },
  { label: "Dogri", key: "doi" },
  { label: "Dombe", key: "dov" },
  { label: "Dutch", key: "nl" },
  { label: "Dzongkha", key: "dz" },
  { label: "English", key: "en" },
  { label: "Esperanto", key: "eo" },
  { label: "Estonian", key: "et" },
  { label: "Ewe", key: "ee" },
  { label: "Fijian", key: "fj" },
  { label: "Filipino (Tagalog)", key: "fil" },
  { label: "Finnish", key: "fi" },
  { label: "French", key: "fr" },
  { label: "French (French)", key: "fr-FR" },
  { label: "French (Canadian)", key: "fr-CA" },
  { label: "Frisian", key: "fy" },
  { label: "Fulfulde", key: "ff" },
  { label: "Ga", key: "gaa" },
  { label: "Galician", key: "gl" },
  { label: "Ganda (Luganda)", key: "lg" },
  { label: "Georgian", key: "ka" },
  { label: "German", key: "de" },
  { label: "Greek", key: "el" },
  { label: "Gujarati", key: "gu" },
  { label: "Haitian Creole", key: "ht" },
  { label: "Hakha Chin", key: "cnh" },
  { label: "Hausa", key: "ha" },
  { label: "Hawaiian", key: "haw" },
  { label: "Hebrew", key: "he" },
  { label: "Hiligaynon", key: "hil" },
  { label: "Hindi", key: "hi" },
  { label: "Hmong", key: "hmn" },
  { label: "Hungarian", key: "hu" },
  { label: "Icelandic", key: "is" },
  { label: "Igbo", key: "ig" },
  { label: "Iloko", key: "ilo" },
  { label: "Indonesian", key: "id" },
  { label: "Irish", key: "ga" },
  { label: "Italian", key: "it" },
  { label: "Japanese", key: "ja" },
  { label: "Javanese", key: "jv" },
  { label: "Kannada", key: "kn" },
  { label: "Kazakh", key: "kk" },
  { label: "Khmer", key: "km" },
  { label: "Kinyarwanda", key: "rw" },
  { label: "Korean", key: "ko" },
  { label: "Kurdish (Kurmanji)", key: "ku" },
  { label: "Kurdish (Sorani)", key: "ckb" },
  { label: "Lao", key: "lo" },
  { label: "Latin", key: "la" },
  { label: "Latvian", key: "lv" },
  { label: "Lithuanian", key: "lt" },
  { label: "Luxembourgish", key: "lb" },
  { label: "Macedonian", key: "mk" },
  { label: "Malay", key: "ms" },
  { label: "Malayalam", key: "ml" },
  { label: "Maltese", key: "mt" },
  { label: "Maori", key: "mi" },
  { label: "Marathi", key: "mr" },
  { label: "Mongolian", key: "mn" },
  { label: "Nepali", key: "ne" },
  { label: "Norwegian", key: "no" },
  { label: "Pashto", key: "ps" },
  { label: "Persian", key: "fa" },
  { label: "Polish", key: "pl" },
  { label: "Portuguese", key: "pt" },
  { label: "Punjabi", key: "pa" },
  { label: "Romanian", key: "ro" },
  { label: "Russian", key: "ru" },
  { label: "Serbian", key: "sr" },
  { label: "Slovak", key: "sk" },
  { label: "Slovenian", key: "sl" },
  { label: "Somali", key: "so" },
  { label: "Spanish", key: "es" },
  { label: "Swahili", key: "sw" },
  { label: "Swedish", key: "sv" },
  { label: "Thai", key: "th" },
  { label: "Turkish", key: "tr" },
  { label: "Ukrainian", key: "uk" },
  { label: "Urdu", key: "ur" },
  { label: "Vietnamese", key: "vi" },
  { label: "Welsh", key: "cy" },
  { label: "Yoruba", key: "yo" },
  { label: "Zulu", key: "zu" },
];

export default languageCodes;
